Update DynamoDB Docs, replaced shell with aws cli command
quarkiverse/quarkus-amazon-services pull request #251
Opened 2022-08-25 19:51 UTC by hamburml

2022-08-29 13:27 UTC, gsmet requested changes
Thanks, I added a few suggestions.

Would you be interested in having a look at the other guides? They all have the same issue.

2022-08-29 13:27 UTC, gsmet commented on docs/modules/ROOT/pages/amazon-dynamodb.adoc
>  ----
```suggestion
[source,json]
----
```

2022-08-29 13:27 UTC, gsmet commented on docs/modules/ROOT/pages/amazon-dynamodb.adoc
> +You should see this in your terminal. That's it, DynamoDB runs locally.
```suggestion
You should see the output above in your terminal. That's it, DynamoDB runs locally.
```

2022-08-29 13:27 UTC, gsmet commented on docs/modules/ROOT/pages/amazon-dynamodb.adoc
> +=== Create the QuakrusFruits Table
```suggestion
=== Create the QuarkusFruits Table
```

2022-08-29 15:44 UTC, hamburml commented
I'll try, but I did not used the other aws parts of this extension. Should be mostly a port replacement I think.

2022-09-22 14:10 UTC, gsmet approved these changes
I rebased and squashed. Let's get this in!

2022-09-22 14:40 UTC, gsmet commented
@scrocquesel I'm merging this but I wonder if we should adjust the documentation now that we have the dev services?

2022-09-22 14:40 UTC, merged

2022-09-22 14:40 UTC, gsmet commented
Thanks for the updates.